Repository Bonotto/INE5420-CG, pull requests merged in 2019-04, with the labels that each got.

#16 Third work
  src/control/main_control.hpp
  src/model/geometry.hpp
  src/model/line.hpp
  src/model/point.hpp
  src/model/polygon.hpp
  src/model/rectangle.hpp
  src/model/shape.hpp
  src/model/viewport.hpp
  src/model/window.hpp
  src/view/interface.glade
Labels: Feature, enhancement

#24 Remove anormalization
  src/control/main_control.hpp
  src/model/shape.hpp
  src/model/viewport.hpp
  src/model/window.hpp
Labels: enhancement

#25 [view] Clipping a Point
  src/config/traits.hpp
  src/control/main_control.hpp
  src/model/point.hpp
  src/model/shape.hpp
Labels: feature, required

#26 Fourth Work
  src/control/main_control.hpp
  src/model/line.hpp
  src/model/point.hpp
  src/model/polygon.hpp
  src/model/rectangle.hpp
  src/view/interface.glade
Labels: feature

#27 Final fourth work
  src/control/main_control.hpp
  src/model/geometry.hpp
  src/model/line.hpp
  src/model/point.hpp
  src/model/polygon.hpp
  src/model/rectangle.hpp
  src/model/shape.hpp
  src/model/viewport.hpp
  src/model/window.hpp
  src/view/interface.glade
Labels: enhancement, feature
